import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import udp.parse.UnifiedDiff;
import udp.parse.UnifiedDiffParser;
import udp.parse.util.UnifiedDiffParserCreator;

import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) throws JsonProcessingException {
        System.out.println(new App().getDiffInfo(args[0]));
    }

    public String getDiffInfo(String diffContent) throws JsonProcessingException {
        UnifiedDiffParser unifiedDiffParser =
                UnifiedDiffParserCreator.getInstance().create();
        List<UnifiedDiff> unifiedDiffs = unifiedDiffParser.parse(diffContent);
        return new ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(unifiedDiffs.get(0));
    }
}
